version: '3.8'

services:

  backend:
    build:
      context: ./python
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./python:/python:cached
    ports:
      - "3001:3001"
      - "5678:5678"
    command: >
      env FLASK_APP=src.app python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 -m flask run --host=0.0.0.0
    depends_on:
      - db
    environment:
      - PYTHONPATH=/python/src

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./frontend:/frontend:cached
      - /frontend/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "start"]

  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: gitpod
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example
    volumes:
      - pgdata:/var/lib/postgresql/data

  android-builder:
    build:
      context: ./android
      dockerfile: Dockerfile
    volumes:
      - ./android:/project
    ports:
      - "5005:5005"

volumes:
  pgdata:
